# Generated by Django 3.1.2 on 2021-12-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('units', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='term',
            name='courses',
            field=models.ManyToManyField(blank=True, to='core.Course'),
        ),
    ]
