# Generated by Django 3.1.2 on 2021-12-02 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211201_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedwork',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.term'),
            preserve_default=False,
        ),
    ]
