# Generated by Django 3.1.2 on 2021-12-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20211214_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedwork',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='categories', to='core.Course'),
        ),
        migrations.AlterField(
            model_name='plannedwork',
            name='offering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.offering'),
        ),
        migrations.AlterField(
            model_name='track',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='core.Course'),
        ),
    ]
