# Generated by Django 3.1.2 on 2021-12-29 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_auto_20211227_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termplan',
            name='approval',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='termplan',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='termPlans', to=settings.AUTH_USER_MODEL),
        ),
    ]
