# Generated by Django 3.1.2 on 2022-02-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_currentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedwork',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.CreateModel(
            name='TrackRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requiredHours', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.track')),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='categories'
        ),
        migrations.AddField(
            model_name='track',
            name='categories',
            field=models.ManyToManyField(blank=True, through='core.TrackRequirement', to='core.Category'),
        ),
    ]
