# Generated by Django 3.1.2 on 2022-03-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20220209_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedwork',
            name='completionStatus',
            field=models.CharField(default=None, max_length=20, null=True),
            preserve_default=False,
        ),
    ]
