# Generated by Django 3.1.2 on 2022-04-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_plannedwork_completionstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='startTerm',
            new_name='term',
        ),
    ]
