# Generated by Django 3.1.2 on 2022-04-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20220408_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
