# Generated by Django 3.1.2 on 2022-04-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20220411_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackrequirement',
            name='requiredHours',
            field=models.CharField(max_length=100),
        ),
    ]
