# Generated by Django 3.1.2 on 2022-04-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20220411_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackrequirement',
            name='requiredHours',
            field=models.CharField(help_text="Will display as plain text.  You may enter a range such as '5-6'", max_length=100),
        ),
    ]
