# Generated by Django 3.1.2 on 2022-04-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220413_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='always_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='term',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='term',
            field=models.ForeignKey(help_text='This is the starting term for the track.', on_delete=django.db.models.deletion.CASCADE, to='core.term'),
        ),
    ]
