# Generated by Django 3.1.2 on 2022-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_faculty_always_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='termplan',
            name='first_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='termplan',
            name='second_approval',
            field=models.BooleanField(default=False),
        ),
    ]
