apiVersion: v1
kind: Service
metadata:
  name: pow-submission
spec:
  ports:
  - port: 8080
  selector:
    app: pow-submission
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pow-submission
spec:
  selector:
    matchLabels:
      app: pow-submission
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pow-submission
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: pow-submission-sites-enabled-configmap
        - name: staticfiles
          emptyDir: {}
      initContainers:
        - name: migrate
          image: jmwhorton/pow_submission:latest
          env:
          - name: POW_DATABASE_HOST
            value: database
          - name: POW_DATABASE_USER
            valueFrom:
                secretKeyRef:
                    name: pow-secret
                    key: postgresql_username
          - name: POW_DATABASE_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: pow-secret
                    key: postgresql_password
          - name: POW_DJANGO_SECRET_KEY
            valueFrom:
                secretKeyRef:
                    name: pow-secret
                    key: django_secret_key
          command: ["python3", "manage.py", "migrate"]
        - name: collectstatic
          image: jmwhorton/pow_submission:latest
          env:
          - name: POW_DATABASE_HOST
            value: database
          - name: POW_DATABASE_USER
            valueFrom:
                secretKeyRef:
                    name: pow-secret
                    key: postgresql_username
          - name: POW_DATABASE_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: pow-secret
                    key: postgresql_password
          - name: POW_DJANGO_SECRET_KEY
            valueFrom:
                secretKeyRef:
                    name: pow-secret
                    key: django_secret_key
          command: ["python3", "manage.py", "collectstatic", "--noinput"]
          volumeMounts:
            - name: staticfiles
              mountPath: /var/www/html
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d/
          - name: staticfiles
            mountPath: /var/www/html
      - name: pow-submission 
        image: jmwhorton/pow_submission:latest
        env:
        - name: POW_DATABASE_HOST
          value: database
        - name: POW_DATABASE_USER
          valueFrom:
              secretKeyRef:
                  name: pow-secret
                  key: postgresql_username
        - name: POW_DATABASE_PASSWORD
          valueFrom:
              secretKeyRef:
                  name: pow-secret
                  key: postgresql_password
        - name: POW_DJANGO_SECRET_KEY
          valueFrom:
              secretKeyRef:
                  name: pow-secret
                  key: django_secret_key
        - name: GOOGLE_RECAPTCHA_SECRET_KEY
          valueFrom:
              secretKeyRef:
                  name: pow-secret
                  key: captcha_secret_key
        - name: GOOGLE_RECAPTCHA_SITE_KEY
          valueFrom:
              secretKeyRef:
                  name: pow-secret
                  key: captcha_site_key
        - name: LOGIN_URL
          valueFrom:
              secretKeyRef:
                  name: pow-secret
                  key: login_url
        ports:
        - containerPort: 3000
          protocol: TCP
