# Generated by Django 3.1.2 on 2021-12-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20211214_1543'),
        ('users', '0004_potentialuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduser',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.track'),
        ),
    ]
