# Generated by Django 3.1.2 on 2022-01-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_faculty'),
        ('users', '0005_aduser_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduser',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faculty'),
        ),
    ]
