# Generated by Django 3.1.2 on 2022-03-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_logintoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintoken',
            name='token',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
