# Generated by Django 3.1.2 on 2022-03-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220318_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduser',
            name='always_notify',
            field=models.BooleanField(default=True),
        ),
    ]
