# Generated by Django 3.1.2 on 2022-04-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_aduser_always_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduser',
            name='always_notify',
            field=models.BooleanField(default=False),
        ),
    ]
